
export enum Unit {
    Integer = "integer",
    IntegerRounded = "integerRounded",
    IntegerPerMonth = "integerPerMonth",
    IntegerPerHour = "integerPerHour",
    FloatSingleFraction = "floatSingleFraction",
    FloatTwoFractions = "floatTwoFractions",
    FloatThreeFractions = "floatThreeFractions",
    Percentage = "percentage",
    PercentageSingleFraction = "percentageSingleFraction",
    Angle = "angle",
    Length = "length",
    Area = "area",
    Volume = "volume",
    VolumePerMonth = "volumePerMonth",
    Weight = "weight",
    WeightPerCell = "weightPerCell",
    WeightPerMonth = "weightPerMonth",
    Power = "power",
    Energy = "energy",
    DataRate = "dataRate",
    DataBytes = "dataBytes",
    DataMegabytes = "dataMegabytes",
    Money = "money",
    MoneyPerCell = "moneyPerCell",
    MoneyPerMonth = "moneyPerMonth",
    MoneyPerHour = "moneyPerHour",
    MoneyPerDistance = "moneyPerDistance",
    MoneyPerDistancePerMonth = "moneyPerDistancePerMonth",
    BodiesPerMonth = "bodiesPerMonth",
    XP = "xp",
    Temperature = "temperature",
    NetElevation = "netElevation"
}
